### PR TITLE
Added custom offset for static antiaim

### PR DESCRIPTION
**Pull request by Turbonator0**

### CODE REVIEW

**Comment by ArnoldasMk** [comment]
Source?

**Comment by Turbonator0** [comment]
What?

**Comment by ArnoldasMk** [comment]
Nvm, thought You pasted from somewhere else, also you You need to add it into settings.cpp, because it must save into the config and load from it.

**Comment by Turbonator0** [comment]
Will do.

**Comment by Turbonator0** [comment]
Now it should work

**Comment by ArnoldasMk** [comment]
Thanks.

**Pull request merged**
